// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.3
// source: osm.proto

package osm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Nominatim
type Nominatim struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       string               `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Properties *NominatimProperties `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	Bbox       *NominatimBbox       `protobuf:"bytes,3,opt,name=bbox,proto3" json:"bbox,omitempty"`
	Geometry   []*NominatimGeometry `protobuf:"bytes,4,rep,name=geometry,proto3" json:"geometry,omitempty"`
}

func (x *Nominatim) Reset() {
	*x = Nominatim{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nominatim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nominatim) ProtoMessage() {}

func (x *Nominatim) ProtoReflect() protoreflect.Message {
	mi := &file_osm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nominatim.ProtoReflect.Descriptor instead.
func (*Nominatim) Descriptor() ([]byte, []int) {
	return file_osm_proto_rawDescGZIP(), []int{0}
}

func (x *Nominatim) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Nominatim) GetProperties() *NominatimProperties {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Nominatim) GetBbox() *NominatimBbox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *Nominatim) GetGeometry() []*NominatimGeometry {
	if x != nil {
		return x.Geometry
	}
	return nil
}

type NominatimProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaceId     int64  `protobuf:"varint,1,opt,name=placeId,proto3" json:"placeId,omitempty"`
	OsmId       int32  `protobuf:"varint,2,opt,name=osmId,proto3" json:"osmId,omitempty"`
	DisplayName string `protobuf:"bytes,3,opt,name=displayName,proto3" json:"displayName,omitempty"`
	PlaceRank   int32  `protobuf:"varint,4,opt,name=placeRank,proto3" json:"placeRank,omitempty"`
	Category    string `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Type        string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	OsmType     string `protobuf:"bytes,7,opt,name=osmType,proto3" json:"osmType,omitempty"`
}

func (x *NominatimProperties) Reset() {
	*x = NominatimProperties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NominatimProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NominatimProperties) ProtoMessage() {}

func (x *NominatimProperties) ProtoReflect() protoreflect.Message {
	mi := &file_osm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NominatimProperties.ProtoReflect.Descriptor instead.
func (*NominatimProperties) Descriptor() ([]byte, []int) {
	return file_osm_proto_rawDescGZIP(), []int{1}
}

func (x *NominatimProperties) GetPlaceId() int64 {
	if x != nil {
		return x.PlaceId
	}
	return 0
}

func (x *NominatimProperties) GetOsmId() int32 {
	if x != nil {
		return x.OsmId
	}
	return 0
}

func (x *NominatimProperties) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *NominatimProperties) GetPlaceRank() int32 {
	if x != nil {
		return x.PlaceRank
	}
	return 0
}

func (x *NominatimProperties) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *NominatimProperties) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NominatimProperties) GetOsmType() string {
	if x != nil {
		return x.OsmType
	}
	return ""
}

type NominatimBbox struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry []float32 `protobuf:"fixed32,1,rep,packed,name=entry,proto3" json:"entry,omitempty"`
}

func (x *NominatimBbox) Reset() {
	*x = NominatimBbox{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NominatimBbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NominatimBbox) ProtoMessage() {}

func (x *NominatimBbox) ProtoReflect() protoreflect.Message {
	mi := &file_osm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NominatimBbox.ProtoReflect.Descriptor instead.
func (*NominatimBbox) Descriptor() ([]byte, []int) {
	return file_osm_proto_rawDescGZIP(), []int{2}
}

func (x *NominatimBbox) GetEntry() []float32 {
	if x != nil {
		return x.Entry
	}
	return nil
}

type NominatimGeometry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        string                  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Coordinates []*NominatimCoordinates `protobuf:"bytes,2,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
}

func (x *NominatimGeometry) Reset() {
	*x = NominatimGeometry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NominatimGeometry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NominatimGeometry) ProtoMessage() {}

func (x *NominatimGeometry) ProtoReflect() protoreflect.Message {
	mi := &file_osm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NominatimGeometry.ProtoReflect.Descriptor instead.
func (*NominatimGeometry) Descriptor() ([]byte, []int) {
	return file_osm_proto_rawDescGZIP(), []int{3}
}

func (x *NominatimGeometry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NominatimGeometry) GetCoordinates() []*NominatimCoordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type NominatimCoordinates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat float32 `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon float32 `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
}

func (x *NominatimCoordinates) Reset() {
	*x = NominatimCoordinates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NominatimCoordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NominatimCoordinates) ProtoMessage() {}

func (x *NominatimCoordinates) ProtoReflect() protoreflect.Message {
	mi := &file_osm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NominatimCoordinates.ProtoReflect.Descriptor instead.
func (*NominatimCoordinates) Descriptor() ([]byte, []int) {
	return file_osm_proto_rawDescGZIP(), []int{4}
}

func (x *NominatimCoordinates) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *NominatimCoordinates) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

var File_osm_proto protoreflect.FileDescriptor

var file_osm_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6f, 0x73, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6f, 0x73, 0x6d,
	0x22, 0xb5, 0x01, 0x0a, 0x09, 0x4e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6d, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x38, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x73, 0x6d, 0x2e, 0x4e, 0x6f, 0x6d,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6d, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x04,
	0x62, 0x62, 0x6f, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x73, 0x6d,
	0x2e, 0x4e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6d, 0x42, 0x62, 0x6f, 0x78, 0x52, 0x04,
	0x62, 0x62, 0x6f, 0x78, 0x12, 0x32, 0x0a, 0x08, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x73, 0x6d, 0x2e, 0x4e, 0x6f, 0x6d,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6d, 0x47, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x52, 0x08,
	0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x22, 0xcf, 0x01, 0x0a, 0x13, 0x4e, 0x6f, 0x6d,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6d, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x73,
	0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x73, 0x6d, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x61, 0x6e, 0x6b, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x61, 0x6e, 0x6b,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6f, 0x73, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6f, 0x73, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x22, 0x25, 0x0a, 0x0d, 0x4e, 0x6f,
	0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6d, 0x42, 0x62, 0x6f, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72,
	0x79, 0x22, 0x64, 0x0a, 0x11, 0x4e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6d, 0x47, 0x65,
	0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x6f,
	0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x6f, 0x73, 0x6d, 0x2e, 0x4e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6d, 0x43,
	0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72,
	0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x22, 0x3a, 0x0a, 0x14, 0x4e, 0x6f, 0x6d, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6d, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x61,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03,
	0x6c, 0x6f, 0x6e, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x69, 0x63, 0x64, 0x65, 0x76, 0x2f, 0x6f, 0x73, 0x6d, 0x5f, 0x70, 0x6f, 0x6c,
	0x79, 0x5f, 0x68, 0x61, 0x72, 0x76, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x6f, 0x73, 0x6d, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_osm_proto_rawDescOnce sync.Once
	file_osm_proto_rawDescData = file_osm_proto_rawDesc
)

func file_osm_proto_rawDescGZIP() []byte {
	file_osm_proto_rawDescOnce.Do(func() {
		file_osm_proto_rawDescData = protoimpl.X.CompressGZIP(file_osm_proto_rawDescData)
	})
	return file_osm_proto_rawDescData
}

var file_osm_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_osm_proto_goTypes = []interface{}{
	(*Nominatim)(nil),            // 0: osm.Nominatim
	(*NominatimProperties)(nil),  // 1: osm.NominatimProperties
	(*NominatimBbox)(nil),        // 2: osm.NominatimBbox
	(*NominatimGeometry)(nil),    // 3: osm.NominatimGeometry
	(*NominatimCoordinates)(nil), // 4: osm.NominatimCoordinates
}
var file_osm_proto_depIdxs = []int32{
	1, // 0: osm.Nominatim.properties:type_name -> osm.NominatimProperties
	2, // 1: osm.Nominatim.bbox:type_name -> osm.NominatimBbox
	3, // 2: osm.Nominatim.geometry:type_name -> osm.NominatimGeometry
	4, // 3: osm.NominatimGeometry.coordinates:type_name -> osm.NominatimCoordinates
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_osm_proto_init() }
func file_osm_proto_init() {
	if File_osm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_osm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nominatim); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NominatimProperties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NominatimBbox); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NominatimGeometry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NominatimCoordinates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_osm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osm_proto_goTypes,
		DependencyIndexes: file_osm_proto_depIdxs,
		MessageInfos:      file_osm_proto_msgTypes,
	}.Build()
	File_osm_proto = out.File
	file_osm_proto_rawDesc = nil
	file_osm_proto_goTypes = nil
	file_osm_proto_depIdxs = nil
}
